park_spot_monitor/main_app/urls.py
from django.urls import path
from . import views

app_name = 'main_app'

urlpatterns = [

path('', views.main, name='main'),

]

park_spot_monitor/park_spot_monitor/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from admin_app.admin import admin_site

urlpatterns = [
    path('mainadmin/', admin_site.urls),
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path("users/", include("users.urls")),
    path('upload/', include('number_recognition.urls')),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

park_spot_monitor/users/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from .views import RegisterView, ResetPasswordView, logout_view, add_plate, show_plates, manage_plate, delete_plate,blocked_account_view, generate_report_csv, show_balance, top_up_balance, sessions_history


from .forms import LoginForm

app_name = "users"

urlpatterns = [
     path("signup/", RegisterView.as_view(), name='register'),
     path("login/", LoginView.as_view(template_name='users/signin.html', authentication_form=LoginForm,
                                     redirect_authenticated_user=True), name='login'),
     path("logout/", logout_view, name="logout"),
     path('reset-password/', ResetPasswordView.as_view(), name='password_reset'),
     path('reset-password/done/', PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
          name='password_reset_done'),
     path('reset-password/confirm/<uidb64>/<token>/',
          PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html',
                                             success_url='/users/reset-password/complete/'),
          name='password_reset_confirm'),
     path('reset-password/complete/',
          PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
          name='password_reset_complete'),
     path('show_plates/', show_plates, name='show_plates'),
     path('manage_plate/<int:plate_id>', manage_plate, name='manage_plate'),
     path('add_plate/', add_plate, name='add_plate'),
     path('blocked_account/', blocked_account_view, name='blocked_account'),
     path('delete_plate/<int:plate_id>', delete_plate, name='delete_plate'),
     path('generate_report_csv/', generate_report_csv, name='generate_report_csv'),
     path('show_balance/', show_balance, name='show_balance'),
     path('top_up_balance/', top_up_balance, name='top_up_balance'),
     path('sessions_history/', sessions_history, name='sessions_history')
]

park_spot_monitor/main_app/models.py
from django.db import models

# Create your models here.

park_spot_monitor/main_app/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from users.models import Balance


@login_required
def main(request):
    # Check if Balance object exists for the authenticated user
    balance, created = Balance.objects.get_or_create(user=request.user)

    # If you need to do something with the created object, you can
    # For example, initialize some default balance value
    if created:
        balance.amount = 0  # Set default balance amount
        balance.save()

    return render(request, 'main_app/index.html', {"title": "Main page"})

park_spot_monitor/main_app/templates/main_app/balance_insufficient.html
<!DOCTYPE html>
<html>
<head>
    <title>Insufficient Balance</title>
</head>
<body>
    <h1>Your balance is insufficient to access the parking.</h1>
    <p>Please contact the administration for assistance.</p>
</body>
</html>

park_spot_monitor/main_app/templates/main_app/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">

    <link href='https://fonts.googleapis.com/css?family=Noto Sans' rel='stylesheet'>
    <link href='https://fonts.googleapis.com/css?family=Roboto' rel='stylesheet'>
    <link href='https://fonts.googleapis.com/css?family=Inter' rel='stylesheet'>

    {% load static %}
    <link rel="stylesheet" href="{% static 'main_app/styles.css' %}">
    <link rel="stylesheet" href="{% static 'main_app/docs.css' %}">
    <link rel="stylesheet" href="{% static 'main_app/css/all.min.css' %}">
    <link rel="stylesheet" href="{% static 'number_recognition/styles.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">

    <style>
        /* Основні стилі */
        body {
            background-image: url('{% static "main_app/background.jpg" %}');
            background-size: cover;
            background-repeat: no-repeat;
        }

        /* Анімація для кнопки навігації */
        .nav-link {
            transition: background-color 0.3s ease;
        }

        .nav-link.active {
            background-color: #007bff; /* Змінюємо колір активної кнопки */
        }
    </style>


    <title>{{title}}</title>
</head>
<body>

<main class="d-flex flex-nowrap">
    <h1 class="visually-hidden">Sidebars examples</h1>

    <div class="sidebar d-flex flex-column flex-shrink-0 p-3 text-bg-custom" style="width: 280px;">
        <a href="/" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto text-white text-decoration-none">
            <svg class="bi pe-none me-2" width="10" height="32"><use xlink:href="#bootstrap"/></svg>
            <img src="{% static 'main_app/logo-main.svg' %}" width="60" height="60" >
            <span class="fs-4">AI Parking</span>
        </a>
        <hr>
        <ul class="nav nav-pills flex-column">
            <li>
                <a class="nav-link" href="/">
                    <i class="fa-solid fa-home"></i>
                    <span class="nav-item mx-auto">Home</span>
                </a>
            </li>
            {% if user.is_authenticated %}
            <li>
                <a class="nav-link text-white" href="{% url 'users:show_balance' %}">
                    <i class="fa-solid fa-dollar"></i>
                    <span class="nav-item">Your balance</span>
                </a>
            </li>
            <li>
                <a class="nav-link text-white" href="{% url 'users:show_plates' %}">
                    <i class="fa-solid fa-list"></i>
                    <span class="nav-item">Your plates</span>
                </a>
            </li>
            <li>
                <a class="nav-link text-white" href="{% url 'users:sessions_history' %}">
                    <i class="fa-solid fa-list"></i>
                    <span class="nav-item">Sessions history</span>
                </a>
            </li>
            <li>
                <a class="nav-link text-white" href="{% url 'number_recognition' %}">
                    <i class="fa-solid fa-camera"></i>
                    <span class="nav-item">Recognize a plate</span>
                </a>
            </li>
            <li>
                <a class="nav-link text-white" href="{% url 'users:logout' %}">
                    <i class="fa-solid fa-sign-out"></i>
                    <span class="nav-item">Logout</span>
                </a>
            </li>
            {% else %}
            <li>
                <a class="nav-link text-white" href="{% url 'users:login' %}">
                    <i class="fa-solid fa-user"></i>
                    <span class="nav-item">SignIn</span>
                </a>
            </li>
            <li>
                <a class="nav-link text-white" href="{% url 'users:register' %}">
                    <i class="fa-solid fa-user-check"></i>
                    <span class="nav-item">SignUp</span>
                </a>
            </li>
            {% endif %}
        </ul>
        <hr>
        <div class="mt-auto"> <!-- Pushes content to the bottom -->
            <a href="https://github.com/olegdenko/ParkSpot_Monitor" target="_blank" class="d-flex align-items-center text-white text-decoration-none mt-auto">
                <i class="fab fa-github"></i> <!-- Font Awesome GitHub icon -->
                <span class="ms-2">Project Link</span>
            </a>
        </div>
    </div>

    <div class="b-example-divider b-example-vr"></div>

    <div class="container-fluid">
        {% block content %}
        {% endblock %}
        <div class="flex-wrap">
        </div>
    </div>

</main>

<script>
    document.addEventListener('DOMContentLoaded', function() {
        const buttons = document.querySelectorAll('.nav-link');

        buttons.forEach(button => {
            button.addEventListener('click', function(event) {
                event.preventDefault();
                buttons.forEach(btn => {
                    btn.classList.remove('active');
                });
                this.classList.add('active');
                const url = this.getAttribute('href');
                setTimeout(function() {
                    window.location.href = url;
                }, 300);
            });
        });

        // Встановлюємо клас "active" на основі поточного URL
        buttons.forEach(button => {
            if (button.getAttribute('href') === window.location.pathname) {
                button.classList.add('active');
            }
        });
    });
</script>

</body>
</html>

park_spot_monitor/main_app/templates/main_app/index.html
{% extends "main_app/base.html" %}
{% load static %}

{% block content %}

{% if user.is_authenticated %}

<div class="container mt-5">
    <div class="card shadow border-primary">
        <div class="row g-0">
            <div class="col-md-4">
                <div class="center-content p-4">
                    <img src="{% static 'main_app/human-man.svg' %}" width="128"
                         class="img-fluid rounded-circle" alt="User Image">
                </div>
            </div>
            <div class="col-md-8">
                <div class="card-body">
                    <h2 class="card-title">Welcome, {{user.username}}</h2>
                    <p>Manage parking with computer vision technology. Automatically detect license plates, track parking durations, and calculate parking charges.</p>
                </div>
            </div>
        </div>
    </div>
</div>

{% else %}

<div class="container mt-5 text-center">
    <div class="card border-secondary">
        <div class="card-body">
            <h1 class="display-5 fw-bold">Smart Parking Management</h1>
            <h3 class="display-6 fw-bold">Join us today!</h3>
            <div class="col-lg-6 mx-auto">
                <p class="lead">Sign up now to experience automatic license plate recognition, track parking duration, and manage parking charges seamlessly.</p>
            </div>
        </div>
    </div>
</div>

{% endif %}

<style>
    .center-content {
        display: flex;
        justify-content: center;
        align-items: center;
        height: 100%;
    }

    .card {
        border-radius: 15px;
        border: 1px solid #dee2e6; /* Додано рамку для карточки */
    }

    .card-title {
        margin-top: 20px;
        font-size: 24px;
        font-weight: bold;
    }

    .lead {
        font-size: 16px;
    }

    .rounded-circle {
        border-radius: 50%;
    }

    /* Фон для неввійдених користувачів */
    .container.text-center {
        background-color: #f8f9fa; /* Світло-сірий фон */
        padding: 20px;
        border-radius: 15px;
    }

    /* Змінити рамку для неввійдених користувачів */
    .card.border-secondary {
        border-color: #6c757d; /* Сірий колір рамки */
    }
</style>

{% endblock %}