park_spot_monitor/park_spot_monitor/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from admin_app.admin import admin_site

urlpatterns = [
    path('mainadmin/', admin_site.urls),
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path("users/", include("users.urls")),
    path('upload/', include('number_recognition.urls')),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

park_spot_monitor/users/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from .views import RegisterView, ResetPasswordView, logout_view, add_plate, show_plates, manage_plate, delete_plate,blocked_account_view, generate_report_csv, show_balance, top_up_balance, sessions_history


from .forms import LoginForm

app_name = "users"

urlpatterns = [
     path("signup/", RegisterView.as_view(), name='register'),
     path("login/", LoginView.as_view(template_name='users/signin.html', authentication_form=LoginForm,
                                     redirect_authenticated_user=True), name='login'),
     path("logout/", logout_view, name="logout"),
     path('reset-password/', ResetPasswordView.as_view(), name='password_reset'),
     path('reset-password/done/', PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
          name='password_reset_done'),
     path('reset-password/confirm/<uidb64>/<token>/',
          PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html',
                                             success_url='/users/reset-password/complete/'),
          name='password_reset_confirm'),
     path('reset-password/complete/',
          PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
          name='password_reset_complete'),
     path('show_plates/', show_plates, name='show_plates'),
     path('manage_plate/<int:plate_id>', manage_plate, name='manage_plate'),
     path('add_plate/', add_plate, name='add_plate'),
     path('blocked_account/', blocked_account_view, name='blocked_account'),
     path('delete_plate/<int:plate_id>', delete_plate, name='delete_plate'),
     path('generate_report_csv/', generate_report_csv, name='generate_report_csv'),
     path('show_balance/', show_balance, name='show_balance'),
     path('top_up_balance/', top_up_balance, name='top_up_balance'),
     path('sessions_history/', sessions_history, name='sessions_history')
]

park_spot_monitor/users/models.py
from django.db import models
from django.contrib.auth.models import User
# from django.db.models.signals import post_save
# from django.dispatch import receiver


class Plates(models.Model):
    """
    Represents a vehicle plate registered by a user.

    Attributes:
        plate (str): The plate number.
        user (User): The user who registered the plate.
    """
    # plate = models.CharField(unique=True, max_length=50)
    plate = models.TextField(unique=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.plate} User {self.user.username}"


class Sessions(models.Model):
    """
    Represents a parking session for a vehicle.

    Attributes:
        entrance_time (DateTime): The time when the vehicle entered the parking spot.
        exit_time (DateTime): The time when the vehicle exited the parking spot.
        plate (Plates): The plate associated with the parking session.
    """
    entrance_time = models.DateTimeField(auto_now_add=True)
    exit_time = models.DateTimeField(null=True)
    plate = models.ForeignKey(Plates, on_delete=models.CASCADE)
    total_hours_spent = models.IntegerField(default=0)

    def __str__(self):
        return f"Session for {self.plate.plate}"
    

class Balance(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    balance = models.DecimalField(default=0, max_digits=10, decimal_places=2)

    def __str__(self):
        return f"{self.balance}"


class BlacklistedVehicle(models.Model):
    """
    Represents a blacklisted vehicle.

    Attributes:
        plate (Plates): The plate number of the blacklisted vehicle.
        user (User): The user who blacklisted the vehicle.
        reason (str): The reason for blacklisting the vehicle.
    """
    plate = models.ForeignKey('Plates', on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    reason = models.TextField()

    def __str__(self):
        return f"{self.plate.plate} User {self.user.username}"


# class Profile(models.Model):
#     user = models.OneToOneField(User, on_delete=models.CASCADE)

#     def __str__(self):
#         return self.user.username


# class Balance(models.Model):
#     user = models.OneToOneField(User, on_delete=models.CASCADE)
#     amount = models.DecimalField(max_digits=10, decimal_places=2)

#     def __str__(self):
#         return f"{self.user.username} - ${self.amount}"


# class ParkingRate(models.Model):
#     rate_name = models.CharField(max_length=50)
#     price_per_hour = models.DecimalField(max_digits=5, decimal_places=2)

#     def __str__(self):
#         return f"{self.rate_name} - ${self.price_per_hour} per hour"


class Settings(models.Model):
    """
    Represents system settings.

    Attributes:
        key (str): The key of the setting.
        value (str): The value of the setting.
    """
    key = models.CharField(max_length=255, unique=True)
    value = models.TextField()

    def __str__(self):
        return f"{self.key}: {self.value}"


# @receiver(post_save, sender=User)
# def create_or_update_balance(sender, instance, created, **kwargs):
#     if created:
#         Balance.objects.create(user=instance, amount=0)
#     else:
#         if hasattr(instance, 'balance'):  # Check if 'balance' exists for the user
#             instance.balance.amount = 0
#             instance.balance.save()
#         else:
#             Balance.objects.create(user=instance, amount=0)  # Create 'balance' if it doesn't exist

park_spot_monitor/users/forms.py
from django.shortcuts import render
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.forms import CharField, TextInput, EmailField, EmailInput, PasswordInput, ModelForm

from .models import Plates

class RegisterForm(UserCreationForm):
    username = CharField(max_length=100, required=True, widget=TextInput(attrs={"class": "form-control"}))
    first_name = CharField(max_length=150, required=False, widget=TextInput(attrs={"class": "form-control"}))
    last_name = CharField(max_length=150, required=False, widget=TextInput(attrs={"class": "form-control"}))
    email = EmailField(max_length=150, required=True, widget=EmailInput(attrs={"class": "form-control"}))
    password1 = CharField(max_length=20, min_length=8, required=True,
                          widget=PasswordInput(attrs={"class": "form-control"}))
    password2 = CharField(max_length=20, min_length=8, required=True,
                          widget=PasswordInput(attrs={"class": "form-control"}))

    class Meta:
        model = User
        fields = ("username", "first_name", "last_name", "email", "password1", "password2")


class LoginForm(AuthenticationForm):
    username = CharField(max_length=100, required=True, widget=TextInput(attrs={"class": "form-control"}))
    password = CharField(max_length=20, min_length=8, required=True,
                         widget=PasswordInput(attrs={"class": "form-control"}))

    class Meta:
        model = User
        fields = ("username", "password")


class PlateForm(ModelForm):
    plate = CharField(min_length=4, widget=TextInput())

    class Meta:
        model = Plates
        fields = ['plate']

park_spot_monitor/users/views.py
from django.contrib.auth.views import PasswordResetView
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout
from django.contrib.messages.views import SuccessMessageMixin
from django.shortcuts import redirect
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy
from django.views import View
from django.contrib import messages
from django.http import HttpResponse


from .forms import RegisterForm, PlateForm
from .models import Balance, Sessions, Plates

import csv



@login_required
def logout_view(request):
    """
    Logs out the user and renders a sign-out page.

    :param request: The HTTP request.
    :type request: HttpRequest
    :return: Rendered sign-out page.
    :rtype: HttpResponse
    """
    if request.method == 'GET':
        username = request.user.username
        logout(request)
        return render(request, "users/signout.html", {"title":"Logout user", "username": username})
    return redirect(to="main_app:main")


class RegisterView(View):
    """
    Class-based view for user registration.

    :param View: Base class for all views.
    :type View: django.views.View
    """
    form_class = RegisterForm
    template_name = "users/signup.html"

    def get(self, request):
        """
        Renders the registration form page.

        :param request: The HTTP request.
        :type request: HttpRequest
        :return: Rendered registration form page.
        :rtype: HttpResponse
        """
        return render(request, self.template_name, {"title":"Register new user", "form": self.form_class})

    def post(self, request):
        """
        Handles the submission of the registration form.

        :param request: The HTTP request.
        :type request: HttpRequest
        :return: Redirects to the login page upon successful registration.
        :rtype: HttpResponse
        """
        form = self.form_class(request.POST)
        print(form)
        if form.is_valid():
            form.save()
            username = form.cleaned_data["username"]
            messages.success(request, f'Вітаємо, {username}! Ваш акаунт успішно створений')
            return redirect(to='users:login')
        return render(request, self.template_name, {"form": form})

class ResetPasswordView(SuccessMessageMixin, PasswordResetView):
    """
    Class-based view for password reset.
    """
    template_name = 'users/password_reset.html'
    email_template_name = 'users/password_reset_email.html'
    html_email_template_name = 'users/password_reset_email.html'
    success_url = reverse_lazy('users:password_reset_done')
    success_message = "An email with instructions to reset your password has been sent to %(email)s."
    subject_template_name = 'users/password_reset_subject.txt'


# Plates
@login_required
def show_plates(request):
    """
    Renders the page displaying all registered plates.

    :param request: The HTTP request.
    :type request: HttpRequest
    :return: Rendered page displaying all registered plates.
    :rtype: HttpResponse
    """
    plates = None
    if request.user.is_authenticated:
        plates = Plates.objects.filter(user = request.user)
    
    return render(request, 'users/show_plates.html', {"plates": plates})


@login_required
def manage_plate(request, plate_id):
    """
    Renders the page for managing a specific plate.

    :param request: The HTTP request.
    :type request: HttpRequest
    :param plate_id: The ID of the plate to manage.
    :type plate_id: int
    :return: Rendered page for managing the plate.
    :rtype: HttpResponse
    """
    plate = get_object_or_404(Plates, pk=plate_id)
    return render(request, 'users/manage_plate.html', {"plate": plate})


@login_required
def add_plate(request):
    """
    Adds a new plate for the authenticated user.

    :param request: The HTTP request.
    :type request: HttpRequest
    :return: Redirects to the main app page upon successful addition.
    :rtype: HttpResponse
    """
    form = PlateForm(request.POST)
    if form.is_valid(): 
        new_plate = form.save(commit=False)
        new_plate.user = request.user
        new_plate.save()
        return redirect(to='users:show_plates')
    else:
        return render(request, 'users/add_plate.html', {'form': form})


def blocked_account_view(request):
    """
    Renders the blocked account page.

    :param request: The HTTP request.
    :type request: HttpRequest
    :return: Rendered blocked account page.
    :rtype: HttpResponse
    """
    return render(request, 'users/blocked_account.html')
  

@login_required
def delete_plate(request, plate_id):
    """
    Deletes a plate associated with the authenticated user.

    :param request: The HTTP request.
    :type request: HttpRequest
    :param plate_id: The ID of the plate to delete.
    :type plate_id: int
    :return: Redirects to the page displaying all registered plates.
    :rtype: HttpResponse
    """
    Plates.objects.get(id=plate_id, user_id=request.user.id).delete()
    return redirect(to='users:show_plates')


# Balance
@login_required
def show_balance(request):
    balance = Balance.objects.get(user=request.user)
    return render(request, 'users/show_balance.html', {"balance": balance})


@login_required
def top_up_balance(request):
    balance = Balance.objects.get(user=request.user)
    balance.balance += 10
    balance.save()
    return redirect('users:show_balance')



# Sessions
@login_required
def sessions_history(request):
    sessions = Sessions.objects.filter(plate__user = request.user)
    return render(request, 'users/sessions_history.html', {"sessions": sessions})


@login_required
def generate_report_csv(request):
    """
    Generates and downloads a CSV report of parking sessions.

    :param request: The HTTP request.
    :type request: HttpRequest
    :return: CSV file response containing parking session data.
    :rtype: HttpResponse
    """
    sessions = Sessions.objects.all()

    field_names = ['Plate', 'User', 'Total hours spent', 'Entrance Time', 'Exit Time']

    response = HttpResponse(content_type='text/csv')
    response['Content-Disposition'] = 'attachment; filename="parking_report.csv"'

    writer = csv.DictWriter(response, fieldnames=field_names)
    writer.writeheader()

    for session in sessions:
        writer.writerow({
            'Plate': session.plate.plate,
            'User': session.plate.user.username,
            'Total hours spent': session.total_hours_spent,
            'Entrance Time': session.entrance_time,
            'Exit Time': session.exit_time if session.exit_time else "Not exited yet"
        })
    return response

park_spot_monitor/users/templates/users/add_plate.html
{% extends "main_app/base.html" %}

{% block content %}
{% load static %}
<link rel="stylesheet" href="{% static 'users/styles.css' %}">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">

<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card shadow">
                <div class="card-body">
                    <h1 class="text-center mb-4">Add Plate Number <i class="fas fa-id-card"></i></h1>
                    <form method="POST" action="{% url 'users:add_plate' %}" class="custom-form">
                        {% csrf_token %}

                        <div class="mb-3">
                            <label for="plate" class="form-label">Plate number <i class="fas fa-car"></i>:</label>
                            {{ form.plate }}
                            <div class="text-danger mt-2">{{ form.errors.plate }}</div>
                        </div>

                        <button type="submit" class="btn btn-primary btn-block"><i class="fas fa-save"></i> Submit</button>
                        <button type="reset" class="btn btn-secondary btn-block mt-3"><i class="fas fa-undo"></i> Reset</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

<!--<style>-->
<!--    body {-->
<!--        background-color: #f4f4f4;-->
<!--        font-family: Arial, sans-serif;-->
<!--    }-->

<!--    .card {-->
<!--        border: 1px solid #ccc;-->
<!--        border-radius: 10px;-->
<!--        box-shadow: 0px 3px 10px rgba(0, 0, 0, 0.2);-->
<!--    }-->

<!--    .card-title {-->
<!--        color: #333;-->
<!--        font-weight: 600;-->
<!--    }-->

<!--    .btn-primary {-->
<!--        background-color: #007bff;-->
<!--        border-color: #007bff;-->
<!--    }-->

<!--    .btn-secondary {-->
<!--        background-color: #6c757d;-->
<!--        border-color: #6c757d;-->
<!--    }-->

<!--    .btn-primary:hover, .btn-secondary:hover {-->
<!--        background-color: #0056b3;-->
<!--        border-color: #0056b3;-->
<!--    }-->

<!--    .custom-form {-->
<!--        padding: 30px;-->
<!--        background-color: #f7f7f7;-->
<!--        border-radius: 10px;-->
<!--    }-->

<!--    .fa {-->
<!--        margin-right: 10px;-->
<!--    }-->
<!--</style>-->

{% endblock %}

park_spot_monitor/users/templates/users/blocked_account.html
{% extends "main_app/base.html" %}

{% block content %}
<div class="blocked-container">
    <h2 class="blocked-title">Your account has been blocked</h2>
    <p class="blocked-message">We're sorry, but your account has been blocked. Please contact support for further assistance.</p>
</div>

<style>
    .blocked-container {
        max-width: 600px;
        margin: 50px auto;
        padding: 20px;
        border: 1px solid #ccc;
        border-radius: 5px;
        background-color: #f8f8f8;
        text-align: center;
    }

    .blocked-title {
        font-size: 24px;
        margin-bottom: 20px;
        color: #d9534f; /* Bootstrap's danger color */
    }

    .blocked-message {
        font-size: 18px;
        line-height: 1.5;
        color: #000000; /* білий колір тексту */
    }
</style>
{% endblock %}

park_spot_monitor/users/templates/users/manage_plate.html
{% extends "main_app/base.html" %}
{% load static %}

{% block content %}

<div class="card mt-5" style="max-width: 540px;">
    <h2 style="margin-left: 10px;">{{ plate.plate }}</h2>
    <a href="{% url 'users:delete_plate' plate.id %}" class="btn btn-danger" style="width: 150px;">Delete plate</a>
</div>

{% endblock %}

park_spot_monitor/users/templates/users/password_reset.html
{% extends "main_app/base.html" %}

{% block content %}
{% load static %}
<link rel="stylesheet" href="{% static 'users/styles.css' %}">

<div class="password-reset-container">
    <h2>Password reset</h2>
    <form method="post" class="password-reset-form">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Request password reset</button>
    </form>
</div>


{% endblock %}

park_spot_monitor/users/templates/users/password_reset_complete.html
{% extends "main_app/base.html" %}

{% block content %}
{% load static %}
<link rel="stylesheet" href="{% static 'users/styles.css' %}">

    <h2>Password reset complete!</h2>

{% endblock %}

park_spot_monitor/users/templates/users/password_reset_confirm.html
{% extends "main_app/base.html" %}

{% block content %}

<h2>Enter new password</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Save new password</button>
</form>

{% endblock %}

park_spot_monitor/users/templates/users/password_reset_done.html
{% extends "main_app/base.html" %}

{% block content %}

{% if messages %}
{% for message in messages %}
<div {% if message.tags %} class="alert alert-{{message.tags}}" {% endif %} role="alert">
    {{message}}
</div>
{% endfor %}
{% endif %}

<h2>Password reset request sent</h2>
<p>We've emailed you with instructions on how to reset your password.</p>

{% endblock %}

park_spot_monitor/users/templates/users/password_reset_email.html
{% autoescape off %}
<body>
<p>Hi {{ user.username }},</p>
<p>You requested a password reset for your account. Please follow this link to set a new password:</p>
<p>
    <a href="{{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}">
        Reset password
    </a>
</p>
<p>If you didn't request a password reset, please ignore this email.</p>
<p>Thanks,</p>
<p>The Our Team</p>
{% endautoescape %}

park_spot_monitor/users/templates/users/sessions_history.html
{% extends "main_app/base.html" %}
{% load static %}

{% block head %}
    <link rel="stylesheet" href="{% static 'users/styles.css' %}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
{% endblock %}

{% block content %}
<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card shadow">
                <div class="card-body">
                    <h2 class="card-title text-center mb-4">{{ user.username }} <i class="fas fa-user"></i></h2>
                    <a href="{% url 'users:generate_report_csv' %}" class="btn btn-primary d-block mb-3"><i class="fas fa-download"></i> Download Report</a>
                    <h3 class="card-subtitle mb-3">Your sessions history:</h3>
                    <ul class="list-group">
                        {% for session in sessions %}
                        <li class="list-group-item d-flex justify-content-between align-items-center">
                            <ul>
                                <li>Plate: {{ session.plate.plate }}</li>
                                <li>Entrance time: {{ session.entrance_time }}</li>
                                {% if session.exit_time %}
                                    <li>Exit time: {{ session.exit_time }}</li>
                                    <li>Total hours spent: {{ session.total_hours_spent }}</li>
                                {% else %}
                                    <li>Exit time: Not exited yet</li>
                                {% endif %}
                            </ul>
                        </li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>

<style>
    body {
        background-color: #f4f4f4;
        font-family: Arial, sans-serif;
    }

    .card {
        border: 1px solid #ccc;
        border-radius: 10px;
        box-shadow: 0px 3px 15px rgba(0, 0, 0, 0.2);
    }

    .card-title {
        color: #333;
        font-weight: 600;
    }

    .btn-primary {
        background-color: #007bff;
        border-color: #007bff;
    }

    .btn-primary:hover {
        background-color: #0056b3;
        border-color: #0056b3;
    }

    .list-group-item {
        border: 1px solid #ccc;
    }
</style>

{% endblock %}

park_spot_monitor/users/templates/users/show_balance.html
{% extends "main_app/base.html" %}
{% load static %}

{% block head %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'users/styles.css' %}">
{% endblock %}

{% block content %}

<div class="container mt-5">
    <div class="card shadow">
        <div class="card-body">
            <h2 class="card-title">
                <i class="fas fa-user-circle mr-2"></i> @{{user.username}}
            </h2>
            <h3 class="card-subtitle mb-3 text-muted">
                Your balance: <i>{{balance}}$</i> <i class="fas fa-dollar-sign ml-2"></i>
            </h3>
            <a href="{% url 'users:top_up_balance' %}" class="btn btn-primary" style="margin-left: 10px; width: 250px;">Add 10$ <i class="fas fa-plus-circle ml-2"></i></a>
        </div>
    </div>
</div>

<script src="https://kit.fontawesome.com/a076d05399.js" crossorigin="anonymous"></script>

{% endblock %}

park_spot_monitor/users/templates/users/show_plates.html
{% extends "main_app/base.html" %}
{% load static %}

{% block head %}
    <link rel="stylesheet" href="{% static 'users/styles.css' %}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
{% endblock %}

{% block content %}
<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card shadow">
                <div class="card-body">
                    <h2 class="card-title text-center mb-4">{{ user.username }} <i class="fas fa-user"></i></h2>
                    <a href="{% url 'users:generate_report_csv' %}" class="btn btn-primary d-block mb-3"><i class="fas fa-download"></i> Download Report</a>
                    <h3 class="card-subtitle mb-3">Your plates <i class="fas fa-car"></i>:</h3>
                    <ul class="list-group">
                        {% for plate in plates %}
                        <li class="list-group-item d-flex justify-content-between align-items-center">
                            <a href="{% url 'users:manage_plate' plate.id %}" class="plate-link">{{ plate.plate }}</a>
                            <span class="badge badge-secondary badge-pill">Manage <i class="fas fa-cogs"></i></span>
                        </li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>

<style>
    body {
        background-color: #f4f4f4;
        font-family: Arial, sans-serif;
    }

    .card {
        border: 1px solid #ccc;
        border-radius: 10px;
        box-shadow: 0px 3px 15px rgba(0, 0, 0, 0.2);
    }

    .card-title {
        color: #333;
        font-weight: 600;
    }

    .btn-primary {
        background-color: #007bff;
        border-color: #007bff;
    }

    .btn-primary:hover {
        background-color: #0056b3;
        border-color: #0056b3;
    }

    .list-group-item {
        border: 1px solid #ccc;
    }

    .plate-link {
        color: #333;
        text-decoration: none;
        transition: color 0.3s ease;
    }

    .plate-link:hover {
        color: #007bff;
    }
</style>

{% endblock %}

park_spot_monitor/users/templates/users/signin.html
{% extends "main_app/base.html" %}

{% block content %}
{% load static %}
<link rel="stylesheet" href="{% static 'users/styles.css' %}">

<div class="container mt-5">
    <h1 class="text-center">Sign In</h1>

    <!-- Виводимо Flash сповіщення -->
    {% if messages %}
    {% for message in messages %}
    <div {% if message.tags %} class="alert alert-{{ message.tags }}" {% endif %} role="alert">
        {{ message }}
    </div>
    {% endfor %}
    {% endif %}

    <!-- Обробляємо помилки форми, які не відносяться до полів -->
    {% if form.errors %}
    <div class="alert alert-danger" role="alert">
        {{ form.non_field_errors }}
    </div>
    {% endif %}

    <div class="bd-example">
        <form method="post">
            {% csrf_token %}

            <div class="form-group">
                <label class="form-label">Username:</label>
                <input type="text" name="username" class="form-control" id="id_username">
                <span class="text-danger">{{ form.errors.username }}</span>
            </div>

            <div class="form-group">
                <label class="form-label">Password:</label>
                <input type="password" name="password" class="form-control" id="id_password">
                <span class="text-danger">{{ form.errors.password }}</span>
            </div>

            <button type="submit" class="btn btn-primary btn-block">Sign In</button>

            <a href="/mainadmin/" class="btn btn-secondary btn-block mt-3">Login as admin</a> <!-- Змінив на Bootstrap кнопку -->

            <div class="text-center mt-3">
                <a href="{% url 'users:password_reset' %}" class="small">Forgot Password?</a>
            </div>
        </form>
    </div>
</div>


{% endblock %}

park_spot_monitor/users/templates/users/signout.html
{% extends "main_app/base.html" %}

{% block content %}
{% load static %}
<link rel="stylesheet" href="{% static 'users/styles.css' %}">
<br>
<h3>Logged out: {{username}} </h3>
<br>
<div class="alert alert-info" role="alert" >
    Have you logged-out already? It's so sadly.
</div>
{% endblock %}

park_spot_monitor/users/templates/users/signup.html
{% extends "main_app/base.html" %}

{% block content %}
{% load static %}
<link rel="stylesheet" href="{% static 'users/styles.css' %}">

<div class="container mt-5">
    <h1 class="text-center">Sign Up</h1>
    <div class="bd-example">
        <form method="post">
            {% csrf_token %}

            <div class="form-group">
                <label class="form-label">Username:</label>
                {{ form.username }}
                <span class="text-danger">{{ form.errors.username }}</span>
            </div>

            <div class="form-group">
                <label class="form-label">First Name:</label>
                {{ form.first_name }}
                <span class="text-danger">{{ form.errors.first_name }}</span>
            </div>

            <div class="form-group">
                <label class="form-label">Last Name:</label>
                {{ form.last_name }}
                <span class="text-danger">{{ form.errors.last_name }}</span>
            </div>

            <div class="form-group">
                <label class="form-label">Email:</label>
                {{ form.email }}
                <span class="text-danger">{{ form.errors.email }}</span>
            </div>

            <div class="form-group">
                <label class="form-label">Password:</label>
                {{ form.password1 }}
                <span class="text-danger">{{ form.errors.password1 }}</span>
            </div>

            <div class="form-group">
                <label class="form-label">Confirm Password:</label>
                {{ form.password2 }}
                <span class="text-danger">{{ form.errors.password2 }}</span>
            </div>

            <button type="submit" class="btn btn-primary btn-block">Sign Up</button>
        </form>
    </div>
</div>

<style>
    body {
        background-color: #f4f4f4;
        font-family: Arial, sans-serif;
    }

    .container {
        max-width: 500px;
        background-color: #ffffff;
        padding: 30px;
        border-radius: 10px;
        box-shadow: 0px 3px 10px rgba(0, 0, 0, 0.2);
    }

    .form-label {
        font-weight: bold;
    }

    .form-group {
        margin-bottom: 20px;
    }

    .text-danger {
        color: #dc3545;
        font-size: 0.875rem;
    }

    .btn-primary {
        background-color: #007bff;
        border-color: #007bff;
    }

    .btn-primary:hover {
        background-color: #0056b3;
        border-color: #0056b3;
    }
</style>

{% endblock %}